### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by proprdev** [ren7995/ShortenIt#1]
I’m currently unable to make a pull request as I am on my phone and I cannot fork the repo, but there is a pretty major spelling error in Tweak.m.

https://github.com/ren7995/ShortenIt/blob/17649c7666a7711414cbb6bda0d77fb470ab7fad/Tweak.m#L18

“aboit” is not valid in any word games (shown in https://www.anagrammer.com/crossword/answer/aboit) and it sure isn’t a word I have ever heard of in my life. I believe, from reading the context of the sentence, that you meant the word “about” instead of “aboit”.

The sentence also requires a period at the end.

**Comment by ren7995** [comment]
Ok. I will look into correcting this.

**Comment by ren7995** [comment]
Upon further investigation, it seems I don't give a shit.

**Comment by proprdev** [comment]
Cancelled.
